[WIP] Tensorboard logging and EOS weights
Lucaskabela/UNAST pull request #16
Opened 2021-04-25 12:51 UTC by liaojh1998

This branch is used to test out the new changes (RNN/Transformers).
- Added tensorboard logging for all weights.
- Added EOS weights for loss to focus on stop tokens better.

The code is untested as my code is currently getting `RuntimeError: CUDA error: misaligned address`.

2021-04-25 14:10 UTC, Lucaskabela requested changes

2021-04-25 14:10 UTC, Lucaskabela commented on src/rnn_no_discrim.json
> +    "train_batch_size": 4,
Might be able to try a larger batch size no with the:
`with torch.no_grad():`
in inference!  I can reliably do 16

2021-04-25 14:10 UTC, Lucaskabela commented on src/train.py
> +        self.batch_size = args.train_batch_size
Good insight on splitting this into train/eval batch size!

2021-04-25 14:10 UTC, Lucaskabela commented on src/train.py
> +        text_pred = model.asr(None, ex_mel.to(DEVICE), infer=True).squeeze(dim=0).detach().cpu().numpy()
need to pass lengths here!

2021-04-25 14:10 UTC, Lucaskabela commented on src/train.py
> +        WRITER.add_text(f"{name}/text_gold", sequence_to_text(ex["text"]), step)
We should trim this to length if it is not all ready, same with speech prediction!

2021-04-26 12:22 UTC, liaojh1998 commented
Rebased on top of latest `mel_loss/bill`.

Added:
- Schedulers for changing learning rate for transformers.

Code is tested using train and eval batch size of 8.

Some notes on the `RuntimeError`:
- The error only occurs in `crossmodel_step()`, and specifically, `model.cm_speech_in(mel, mel_len)` every time when trying to do inference on the encoded speech sequence for text.
- The error only occurs on accessing `stop_lens[stop_mask] = i` in the . Try printing `stop_lens` or printing `choice` will result in this error as well.

2021-04-26 12:36 UTC, liaojh1998 commented
`RuntimeError` example log, but happens during `evaluate()` call as well.
![image](https://user-images.githubusercontent.com/22307142/116083261-0c66c680-a662-11eb-8067-1ed31cf428ab.png)

2021-04-27 06:14 UTC, liaojh1998 commented
The RNN optimizations here looks good. Thanks for working on this Lucas!

2021-04-27 23:48 UTC, merged